contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #ensemblrepeatdownload channel"
    url: https://nfcore.slack.com/channels/ensemblrepeatdownload
    about: Discussion about the sanger-tol/ensemblrepeatdownload pipeline
